$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 1  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 2  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 3  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 4  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 5  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 6  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 7  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 8  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 9  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 10  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 11  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 12  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 13  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 14  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 15  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 16  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 17  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 18  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 19  &
$ORACLE_HOME/bin/sqlplus yoda/foo@localhost:1521/orcl @test2 20  &
